### PR TITLE
Make note to wait for travis to finish before tagging

### PR DESCRIPTION
**Pull request by raboof**
otherwise the build on master might also use the tag

### CODE REVIEW

**Comment by raboof** [comment]
I think sbt-dynver is still fine, and this should be fixed at the Travis side: it should be able to distinguish between a build triggered by a push to master and a build triggered by a tag being added. I see there's a `TRAVIS_TAG` environment variable (https://docs.travis-ci.com/user/environment-variables/), I wonder if that is populated when the trigger was a push but a tag was added to that commit since?

**Comment by dwijnand** [comment]
Let's say, best-case scenario, it's not, how do you use that to fix the problem?

**Comment by raboof** [comment]
Only do the 'release' step when `TRAVIS_TAG` is populated?

**Comment by dwijnand** [comment]
That could work for some projects, but in the sbt plugins I've set up I release tags and master builds ("merglies"), so I still run into this problem.

Fundamentally git tags are un-versioned mutable state that shouldn't transparently change build behaviour, IMO.  So I think a better set up is one where git tags just fast-fail a build if they don't match the version (and great lengths would go into removing or minimising version micro-management).

I explored these thoughts with Daniel Spiewak in https://github.com/djspiewak/sbt-spiewak/issues/3.

**Comment by raboof** [comment]
> I release tags and master builds ("merglies")

Good point.

> I explored these thoughts with Daniel Spiewak in djspiewak/sbt-spiewak#3

Also https://github.com/djspiewak/sbt-spiewak/blob/master/versioning.md - interesting!

**Comment by pvlugter** [comment]
Sorry, I read the comment earlier about separating out the commit and tag, and still forgot about it when I actually pushed.

**Comment by dwijnand** [comment]
Here are some other notes with a workaround: https://github.com/dwijnand/sbt-dynver/issues/118

**Pull request merged**
