### PR TITLE
Include aggregateProjectName and product in build output

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
Thanks! @dwijnand got time for a release? :)

**Comment by dwijnand** [comment]
Does tomorrow morning work for you, or do you need it sooner?

**Comment by raboof** [comment]
Tomorrow would be great!

**Comment by dwijnand** [comment]
https://github.com/lightbend/sbt-whitesource/releases/tag/v0.1.7

**Pull request merged**
